### ISSUE TITLE
Join Discord link not working..!!

### ISSUE THREAD

**Issue by athrvvvv** [Dhravya/dhravya#2]
# The link provided in README is'nt working
# See
![Screenshot 2022-04-10 162216](https://user-images.githubusercontent.com/98272709/162614789-29947d4a-4e55-41e7-8c18-8d12f83b366e.png)

**Comment by Dhravya** [comment]
Oh dammit! The invite link expired. https://discord.gg/T8WJxsEG here's the latest one

**Comment by athrvvvv** [comment]
Thx bro :D
